import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillInstagram,
} from "react-icons/ai";
import { BsSun, BsArrowDownCircle } from "react-icons/bs";

import wave from "../public/profile2.png";
import sberrich from "../public/wave4.png";
// import signature from "../public/signature.png";
// import code from "../public/code.png";
// import design from "../public/design.png";
// import cardweb from "../public/card-hello-background.webp";
// import consulting from "../public/consulting.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [languageIndex, setLanguageIndex] = useState(0);
  const languages = ["ⴰⵣⵓⵍ ⴼⵍⴰⵡⵏ", "السلام عليكم", "Bonjour", "Hello"];

  useEffect(() => {
    const timer = setInterval(() => {
      setLanguageIndex((prevIndex) => (prevIndex + 1) % languages.length);
    }, 2000);

    return () => {
      clearInterval(timer);
    };
  }, []);

  return (
    <div className={`bg-gray-200 ${darkMode ? "dark" : ""}`}>
      <Head>
        <title>SamirBerrichi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-200 px-10 dark:bg-gray-900 md:px-20 lg:px-40  duration-300 select-none  animate-fade-in">
        <section className="">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <div className="flex ml-4 relative items-center justify-center">
              <div className="absolute bg-[#b5e3fd]/30 w-[130px] h-[20px] blur-md"></div>
              <div className="rounded-full flex items-center justify-between">
                <span className="text-2xl font-bold tracking-wide font-['Tahu']">
                  S<span className="opacity-100">a</span>
                  <span className="opacity-100">m</span>
                  <span className="opacity-100">i</span>
                  <span className="opacity-100">r</span>
                </span>
                <Image
                  src={sberrich}
                  width={30}
                  height={30}
                  objectFit="contain"
                  alt="sberrich"
                />
                <span className="text-xl font-bold tracking-wide font-['Tahu']">
                  B<span className="opacity-100">e</span>
                  <span className="opacity-100">r</span>
                  <span className="opacity-100">r</span>
                  <span className="opacity-100">i</span>
                  <span className="opacity-100">c</span>
                  <span className="opacity-100">h</span>
                  <span className="opacity-100">i</span>
                  <span className="opacity-100">.</span>
                </span>
              </div>
            </div>
            <ul className="flex items-center justify-between">
              <li>
                <BsSun
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl ho"
                />
              </li>
              <li>
                <BsArrowDownCircle className="cursor-pointer text-2xl ml-12" />
              </li>
            </ul>
          </nav>
          <div className="flex flex-col md:flex-row items-center justify-around dark:text-white ">
            {/* Left Side with Four Cards */}
            <div className="bg-white dark:bg-primary-black min-w-[300px] rounded-[32px] flex flex-col justify-between relative w-full xl:w-1/2 min-h-[300px] p-[32px] dark:bg-primary-black border-2 dark:bg-gray-800 light-border overflow-hidden ">
              <div className="flex justify-between max-w-full">
                <div className="flex flex-row items-center gap-5">
                  <div className="max-w-fit">
                    <div className="relative flex items-center justify-center">
                      <div className="absolute w-[50px] h-[50px] bg-[#b5e3fd]/75 rounded-full flex items-center justify-center blur-md"></div>
                      <Image
                        alt="profile_alt"
                        src={sberrich}
                        width={75}
                        height={75}
                        decoding="async"
                        className="w-22 h-22 relative top-[-4px] left-[-2px]"
                        loading="lazy"
                      />
                    </div>
                  </div>
                  <div>
                    <p>
                      Hello, I’m
                      <span className="font-[Moranga] font-semibold text-xl">
                        Samir.
                      </span>
                    </p>
                    <p className="text-sm text-secondary">FrontEnd Engineer</p>
                  </div>
                </div>
              </div>
              <p className="">
                also known as sberrich, a self-taught
                <span className="font-[Moranga] text-xl font-semibold m-2">
                  frontend developer
                </span>
                originally from Morocco and residing in Khouribga at the moment.
                Currently available for freelance work or full-time jobs. When
                I’m not coding or designing, I enjoy reading books, playing
                football, playing video games, or watching movies. Lately, I've
                started hitting the gym to build some strength, burn calories,
                and I’m enjoying it so far.
              </p>
            </div>

            {/* Right Side with Image */}
            <div className="md:w-1/2">
              <div className="hidden md:block">
                <div>
                  <h2 className=" font-Moranga font-semibold text-2xl ">
                    {languages[languageIndex]} ✋
                  </h2>
                </div>
                <Image
                  src={wave}
                  width={700}
                  height={700}
                  objectFit="contain"
                  alt="wave"
                />
              </div>
            </div>
          </div>
        </section>

      </main>
    </div>
  );
}
